services:
  postgres:
    image: postgres:latest
    container_name: postgres-products
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./init-scripts/:/docker-entrypoint-initdb.d"

  pgadmin:
    image: dpage/pgadmin4 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3005:80"
    restart: unless-stopped
