services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dummy

  pgadmin:
    image: dpage/pgadmin4 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3005:80"
    restart: unless-stopped
