services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword  
      MYSQL_DATABASE: exampledb          
      MYSQL_USER: root                     
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

